# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt-designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, cv2, time, os
import numpy as np
#import WiringPi as wiringpi
#from subprocess import call
#import pygame, sys
#from pygame.locals import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Set QWidget Size
        sizeObject = QtWidgets.QDesktopWidget().screenGeometry(-1)
        window_w, window_h = sizeObject.width(), sizeObject.height()
        MainWindow.resize(window_w, window_h)
        self.CAM_NUM = 0
        self.cap = cv2.VideoCapture()
        self.timer_camera = QtCore.QTimer()
        self.takeFlag = 0
        self.seconds = 3
        
        LeftWidth = int(window_w * 0.7)
        LeftSize = QtCore.QRect(0, 0, LeftWidth, window_h)
        
        RightWidth = window_w - LeftWidth
        RightSize = QtCore.QRect(LeftWidth, 0, RightWidth, window_h)
        
        ################## LEFT ##########################################
        self.LeftLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.LeftLayoutWidget.setGeometry(LeftSize)
        self.LeftLayoutWidget.setObjectName("LeftLayoutWidget")
        self.LeftLayout = QtWidgets.QHBoxLayout(self.LeftLayoutWidget)
        self.LeftLayout.setContentsMargins(0, 0, 0, 0)
        self.LeftLayout.setObjectName("LeftLayout")
        
        self.lblShowCam = QtWidgets.QLabel()
        self.lblShowCam.setFixedSize(LeftWidth, window_h)
        self.lblShowCam.setAutoFillBackground(False)
        
        self.lblShowCap = QtWidgets.QLabel()
        self.lblShowCap.setFixedSize(LeftWidth, window_h)
        self.lblShowCap.setAutoFillBackground(False)
        
        self.LeftLayout.addWidget(self.lblShowCam)
        self.LeftLayout.addWidget(self.lblShowCap)
        
        ################## Right ##########################################
        self.RightLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.RightLayoutWidget.setGeometry(RightSize)
        self.RightLayoutWidget.setObjectName("RightLayoutWidget")
        self.RightLayout = QtWidgets.QHBoxLayout(self.RightLayoutWidget)
        self.RightLayout.setContentsMargins(0, 0, 0, 0)
        self.RightLayout.setObjectName("RightLayout")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RightLayout.addLayout(self.verticalLayout)
              
        self.SnapShopBtn = QtWidgets.QPushButton()
        self.SnapShopBtn.setObjectName("SnapShopBtn")
        self.verticalLayout.addWidget(self.SnapShopBtn)
        
        self.CapBtn = QtWidgets.QPushButton()
        self.CapBtn.setObjectName("CapBtn")
        self.verticalLayout.addWidget(self.CapBtn)
        
        self.DisPlayBtn = QtWidgets.QPushButton()
        self.DisPlayBtn.setObjectName("DisPlayBtn")
        self.verticalLayout.addWidget(self.DisPlayBtn)
        
        self.AIPhotoBtn = QtWidgets.QPushButton()
        self.AIPhotoBtn.setObjectName("AIPhotoBtn")
        self.verticalLayout.addWidget(self.AIPhotoBtn)
        
        fontx = QtGui.QFont()
        fontx.setFamily("kaiti")
        fontx.setPointSize(16)
        
        # Button Style
        btnArrays = [self.AIPhotoBtn, self.SnapShopBtn, self.DisPlayBtn, self.CapBtn]
        btnStyle = '''
            QAIPhotoBtn{color:black}
            QAIPhotoBtn:hover{color:red}
            QAIPhotoBtn{background-color:rgb(78,255,255)}
            QAIPhotoBtn{border:2px}
            QAIPhotoBtn{border-radius:10px}
            QAIPhotoBtn{padding:2px 4px}
        '''
        for i in range(len(btnArrays)):
            btnArrays[i].setFont(fontx)
            btnArrays[i].setStyleSheet(btnStyle)
        
        self.AIPhotoBtn.setMinimumHeight(50)
        self.SnapShopBtn.setMinimumHeight(50)
        self.CapBtn.setMinimumHeight(50)
        self.DisPlayBtn.setMinimumHeight(50)
        
        self.btnGroup = QtWidgets.QButtonGroup(MainWindow)
        self.btnGroup.addButton(self.AIPhotoBtn, 1)
        self.btnGroup.addButton(self.SnapShopBtn, 2)
        self.btnGroup.addButton(self.DisPlayBtn, 3)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeddingShow"))
        self.SnapShopBtn.setText(_translate("MainWindow", "SnapShot"))
        self.CapBtn.setText(_translate("MainWindow", "Capture"))
        self.DisPlayBtn.setText(_translate("MainWindow", "DisPlay"))
        self.AIPhotoBtn.setText(_translate("MainWindow", "AIPhoto"))

    def setupEvent(self, MainWindow):
        self.AIPhotoBtn.clicked.connect(self.AIPhotoEventTrigger)
        self.SnapShopBtn.clicked.connect(self.SnapShopEventTrigger)
        self.DisPlayBtn.clicked.connect(self.DisPlayEventTrigger)
        self.timer_camera.timeout.connect(self.show_camera)
        self.CapBtn.clicked.connect(self.capx)
          
    def SnapShopEventTrigger(self):
        print("SnapShopEventTrigger");
        if self.timer_camera.isActive() == False:
            flag = self.cap.open(self.CAM_NUM,  cv2.CAP_DSHOW)
            if flag == False:
                msg = QtWidgets.QMessageBox.warning(self, u"Warning", u"相機是否有開啟",
                                                    buttons = QtWidgets.QMessageBox.Ok,
                                                    defaultButton = QtWidgets.QMessageBox.Ok)
            else:
                self.timer_camera.start(30)

                #self.button_open_camera.setText(u'closed camera')
        else:
            self.timer_camera.stop()
            self.cap.release()
            self.lblShowCam.clear()
            #self.button_open_camera.setText(u'open camera')
        
    def DisPlayEventTrigger(object):
        print("DisPlayEventTrigger");
        
        
        
    def AIPhotoEventTrigger(self):
        print("AIPhotoEventTrigger");
        

    def show_camera(self):
        if self.takeFlag == 0:
            flag, self.image = self.cap.read()
            show = cv2.resize(self.image, (self.LeftLayoutWidget.width(), self.LeftLayoutWidget.height()))
            show = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
            self.showImage = QtGui.QImage(show.data, show.shape[1], show.shape[0], QtGui.QImage.Format_RGB888)
            self.lblShowCam.setPixmap(QtGui.QPixmap.fromImage(self.showImage))
    
    def CountDown(self, MainWindow):
        self.takeFlag = 1
        counts = self.seconds
        start = time.time()
        time.process_time()
        elapsed = 0
        while elapsed < counts:
            elapsed = time.time() - start
            elapsed_time = int(time.time() - start)
            flag, self.image = self.cap.read()
            if elapsed_time < counts :
                cv2.putText(self.image, str(int(counts - elapsed_time)), (320, 240), cv2.FONT_HERSHEY_SIMPLEX,  5, (0, 255, 255), 5, cv2.LINE_AA)
            show = cv2.resize(self.image, (self.LeftLayoutWidget.width(), self.LeftLayoutWidget.height()))
            show = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
            self.showImage = QtGui.QImage(show.data, show.shape[1], show.shape[0], QtGui.QImage.Format_RGB888)
            self.lblShowCam.setPixmap(QtGui.QPixmap.fromImage(self.showImage))
            cv2.waitKey(1)
        self.takeFlag = 0
    
    def TagDay(self, MainWindow):
        self.takeFlag = 1
        self.takeFlag = 0
        
    def capx(self):
        FName = fr"images\cap{time.strftime('%Y%m%d%H%M%S', time.localtime())}"
        self.CountDown(self)
        cv2.imwrite(FName + ".jpg", self.image)
        self.takeFlag = 1
        flag, self.image = self.cap.read()
        print(self.LeftLayoutWidget.width())
        print(self.LeftLayoutWidget.height())
        cv2.putText(self.image, str("Wedding Day"), (0, 400), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 1, cv2.LINE_AA)
        show = cv2.resize(self.image, (self.LeftLayoutWidget.width(), self.LeftLayoutWidget.height()))
        show = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
        self.showImage = QtGui.QImage(show.data, show.shape[1], show.shape[0], QtGui.QImage.Format_RGB888)
        self.lblShowCam.setPixmap(QtGui.QPixmap.fromImage(self.showImage))
        cv2.waitKey(1)
        self.lblShowCap.setPixmap(QtGui.QPixmap.fromImage(self.showImage))
        self.lblShowCap.setGeometry(0, 0, self.LeftLayoutWidget.width(), self.LeftLayoutWidget.height())
        self.showImage.save(FName + ".jpg", "JPG", 100)
        time.sleep(5)
        self.lblShowCap.setVisible(False)
        self.takeFlag = 0
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setupEvent(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
