# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled-test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AIPhoto import AIPhoto as AI 
from DisplayPhoto import DisplayPhoto as DP 
from SnapShotPhoto import SnapShotPhoto as SSP
import sys, cv2, time, os
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.CAM_NUM = 0
        self.CAP = cv2.VideoCapture()
        self.timeCam = QtCore.QTimer()
        self.takeFlag = 0
        self.seconds = 3
        
        # Set QWidget Size
        sizeObject = QtWidgets.QDesktopWidget().screenGeometry(-1)
        window_w, window_h = sizeObject.width(), sizeObject.height()
        MainWindow.resize(window_w, window_h)
        
        LeftWidth = int(window_w * 0.7)
        self.LeftSize = QtCore.QRect(0, 0, LeftWidth, window_h)
        RightWidth = window_w - LeftWidth
        self.RightSize = QtCore.QRect(LeftWidth, 0, RightWidth, window_h)        
        # End of QWidget Size
        
        # Left
        self.LeftgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LeftgroupBox.setGeometry(self.LeftSize)
        self.LeftgroupBox.setObjectName("LeftgroupBox")
        
        self.LeftgridLayoutWidget = QtWidgets.QWidget(self.LeftgroupBox)
        self.LeftgridLayoutWidget.setGeometry(self.LeftSize)
        self.LeftgridLayoutWidget.setObjectName("LeftgridLayoutWidget")
        
        self.gridLayout_6 = QtWidgets.QGridLayout(self.LeftgridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        self.lblShowCam = QtWidgets.QLabel()
        self.lblShowCam.setFixedSize(LeftWidth, window_h)
        self.lblShowCam.setAutoFillBackground(False)      
        
        self.lblShowCap = QtWidgets.QLabel()
        self.lblShowCap.setFixedSize(LeftWidth, window_h)
        self.lblShowCap.setAutoFillBackground(False)      
        
        self.gridLayout_6.addWidget(self.lblShowCam)
        self.gridLayout_6.addWidget(self.lblShowCap)
        
        # End of Left
        
        # Right
        self.RightgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.RightgroupBox.setGeometry(self.RightSize)
        self.RightgroupBox.setObjectName("RightgroupBox")
        
        ####################################################################
        self.gridLayoutWidget = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, RightWidth, 210))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.btnCamera = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCamera.setObjectName("btnCamera")
        self.gridLayout_3.addWidget(self.btnCamera, 0, 0, 1, 1)
        
        self.btnCap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCap.setObjectName("btnCap")
        self.gridLayout_3.addWidget(self.btnCap, 1, 0, 1, 1)
        
        self.btnCap.setMinimumHeight(100)
        self.btnCamera.setMinimumHeight(100)
        
        ####################################################################
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 240, RightWidth, 250))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 0, 1, 3)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 0, 1, 1)
        
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 1, 1, 1, 1)
        
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 1, 2, 1, 1)
        
        ###################################################################
        
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 2, 0, 1, 1)
        
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_4.addWidget(self.pushButton_8, 2, 1, 1, 1)
        
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 2, 2, 1, 1)
        
        ###################################################################
        
        self.pushButton_3.setMinimumHeight(100)
        self.pushButton_4.setMinimumHeight(50)
        self.pushButton_5.setMinimumHeight(50)
        self.pushButton_6.setMinimumHeight(50)
        self.pushButton_7.setMinimumHeight(50)
        self.pushButton_8.setMinimumHeight(50)
        self.pushButton_9.setMinimumHeight(50)
        
        ###################################################################
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 500, RightWidth, 100))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 0, 0, 1, 1)
        
        self.pushButton_10.setMinimumHeight(100)
        # End of Right
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LeftgroupBox.setTitle(_translate("MainWindow", "顯示"))
        self.RightgroupBox.setTitle(_translate("MainWindow", "功能"))
        self.btnCamera.setText(_translate("MainWindow", "開啟相機"))
        self.btnCap.setText(_translate("MainWindow", "拍照"))
        self.pushButton_3.setText(_translate("MainWindow", "播放"))
        self.pushButton_4.setText(_translate("MainWindow", "中原"))
        self.pushButton_5.setText(_translate("MainWindow", "八分之一"))
        self.pushButton_6.setText(_translate("MainWindow", "登記"))
        self.pushButton_7.setText(_translate("MainWindow", "雀囍"))
        self.pushButton_8.setText(_translate("MainWindow", "Cheeses"))
        self.pushButton_9.setText(_translate("MainWindow", "Live"))
        self.pushButton_10.setText(_translate("MainWindow", "AI 照相"))

    def setupEvent(self, MainWindow):
        self.btnCamera.clicked.connect(lambda:SSP.EventTrigger(self.CAM_NUM, self.CAP, self.timeCam, cv2))
        self.btnCap.clicked.connect(lambda:SSP.TakePictures(self.timeCam, self.takeFlag, self.CAP,cv2, self.LeftSize.width(), self.LeftSize.height(), self.seconds, self.lblShowCam, self.lblShowCap))
        self.timeCam.timeout.connect(lambda:SSP.ShowCamera(self.CAP, cv2, self.LeftSize.width(), self.LeftSize.height(), self.lblShowCam))
        self.pushButton_3.clicked.connect(DP.EventTrigger)
        self.pushButton_10.clicked.connect(AI.EventTrigger)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setupEvent(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
