# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled-test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AIPhoto import AIPhoto as AI 
from DisplayPhoto import DisplayPhoto as DP
from SnapShotPhoto import SnapShotPhoto as SSP
from WEDUI import WEDUI as WUI
import sys, cv2, time, os
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #self.CAM_NUM = 0
        #self.CAP = cv2.VideoCapture()
        #self.timeCam = QtCore.QTimer()
        #self.takeFlag = 0
        #self.seconds = 3
        
        # Set QWidget Size
        sizeObject = QtWidgets.QDesktopWidget().screenGeometry(-1)
        window_w, window_h = sizeObject.width(), sizeObject.height()
        MainWindow.resize(window_w, window_h)
        
        LeftWidth = int(window_w * 0.7)
        self.LeftSize = QtCore.QRect(0, 0, LeftWidth, window_h)
        RightWidth = window_w - LeftWidth
        self.RightSize = QtCore.QRect(LeftWidth, 0, RightWidth, window_h)        
        # End of QWidget Size
        
        WUI.UIObj["LFRAME"] = self.LeftSize
        WUI.UIObj["RFRAME"] = self.RightSize
        
        # Left
        self.LeftgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LeftgroupBox.setGeometry(self.LeftSize)
        self.LeftgroupBox.setObjectName("LeftgroupBox")
        
        self.LeftgridLayoutWidget = QtWidgets.QWidget(self.LeftgroupBox)
        self.LeftgridLayoutWidget.setGeometry(self.LeftSize)
        self.LeftgridLayoutWidget.setObjectName("LeftgridLayoutWidget")
        
        self.gridLayout_6 = QtWidgets.QGridLayout(self.LeftgridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        self.lblShowCam = QtWidgets.QLabel()
        self.lblShowCam.setFixedSize(LeftWidth, window_h)
        self.lblShowCam.setAutoFillBackground(False)      
        
        self.lblShowCap = QtWidgets.QLabel()
        self.lblShowCap.setFixedSize(LeftWidth, window_h)
        self.lblShowCap.setAutoFillBackground(False)      
        
        self.gridLayout_6.addWidget(self.lblShowCam)
        self.gridLayout_6.addWidget(self.lblShowCap)
        
        WUI.UIObj["lblShowCam"] = self.lblShowCam
        WUI.UIObj["lblShowCap"] = self.lblShowCap
        # End of Left
        
        # Right
        self.RightgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.RightgroupBox.setGeometry(self.RightSize)
        self.RightgroupBox.setObjectName("RightgroupBox")
        
        ####################################################################
        self.gridLayoutWidget = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, RightWidth, 210))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.btnCamera = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCamera.setObjectName("btnCamera")
        self.gridLayout_3.addWidget(self.btnCamera, 0, 0, 1, 1)
        
        self.btnCap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCap.setObjectName("btnCap")
        self.gridLayout_3.addWidget(self.btnCap, 1, 0, 1, 1)
        
        self.btnCap.setMinimumHeight(100)
        self.btnCamera.setMinimumHeight(100)
        
        WUI.UIObj["btnCap"] = self.btnCap
        WUI.UIObj["btnCamera"] = self.btnCamera
        
        ####################################################################
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 240, RightWidth, 250))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.btnDisplay = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnDisplay.setObjectName("btnDisplay")
        self.gridLayout_4.addWidget(self.btnDisplay, 0, 0, 1, 3)
        
        self.btnCYCU = QtWidgets.QRadioButton('中原', self.gridLayoutWidget_2)
        #layout.addWidget(self.myradiobutton1, 0, 0)
        
        #self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        #self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.btnCYCU, 1, 0, 1, 1)
        
        self.btnETH = QtWidgets.QRadioButton("八分之一", self.gridLayoutWidget_2)
        #self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.btnETH, 1, 1, 1, 1)
        
        self.btnREG = QtWidgets.QRadioButton("登記", self.gridLayoutWidget_2)
        #self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.btnREG, 1, 2, 1, 1)
        
        ###################################################################
        
        self.btnTRACY = QtWidgets.QRadioButton("雀囍", self.gridLayoutWidget_2)
        self.gridLayout_4.addWidget(self.btnTRACY, 2, 0, 1, 1)
        
        self.btnCHEESES = QtWidgets.QRadioButton("Cheeses", self.gridLayoutWidget_2)
        self.gridLayout_4.addWidget(self.btnCHEESES, 2, 1, 1, 1)
        
        self.btnLIVE = QtWidgets.QRadioButton("現場", self.gridLayoutWidget_2)
        self.gridLayout_4.addWidget(self.btnLIVE, 2, 2, 1, 1)
        
        self.btnGroup = QtWidgets.QButtonGroup(self.gridLayoutWidget_2)
        self.btnGroup.addButton(self.btnCYCU, 1)
        self.btnGroup.addButton(self.btnETH, 2)
        self.btnGroup.addButton(self.btnREG, 3)
        self.btnGroup.addButton(self.btnTRACY, 4)
        self.btnGroup.addButton(self.btnCHEESES, 5)
        self.btnGroup.addButton(self.btnLIVE, 6)
        self.btnLIVE.setChecked(True)
        folder = fr"C:\Users\chaol\Downloads\Project\rpi-camera\images\Live"
        WUI.UIObj["IMGFOLDER"] = folder
        WUI.UIObj["btnGroup"] = self.btnGroup
        DPdict = dict()
        DPdict["CYCU"] = self.btnCYCU
        DPdict["ETH"] = self.btnETH
        DPdict["REG"] = self.btnREG
        DPdict["TRACY"] = self.btnTRACY
        DPdict["CHEESES"] = self.btnCHEESES
        DPdict["LIVE"] = self.btnLIVE
        WUI.UIObj["DPRDIOGroup"] = DPdict
        
        ###################################################################
        
        self.btnDisplay.setMinimumHeight(100)
        self.btnCYCU.setMinimumHeight(50)
        self.btnETH.setMinimumHeight(50)
        self.btnREG.setMinimumHeight(50)
        self.btnTRACY.setMinimumHeight(50)
        self.btnCHEESES.setMinimumHeight(50)
        self.btnLIVE.setMinimumHeight(50)
        
        ###################################################################
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.RightgroupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 500, RightWidth, 100))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.btnAI = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnAI.setObjectName("btnAI")
        self.gridLayout_5.addWidget(self.btnAI, 0, 0, 1, 1)
        
        self.btnAI.setMinimumHeight(100)
        WUI.UIObj["btnAI"] = self.btnAI
        # End of Right
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LeftgroupBox.setTitle(_translate("MainWindow", "顯示"))
        self.RightgroupBox.setTitle(_translate("MainWindow", "功能"))
        self.btnCamera.setText(_translate("MainWindow", "開啟相機"))
        self.btnCap.setText(_translate("MainWindow", "拍照"))
        self.btnDisplay.setText(_translate("MainWindow", "播放"))
        self.btnAI.setText(_translate("MainWindow", "AI 照相"))

    def setupEvent(self, MainWindow):
        self.btnCamera.clicked.connect(lambda:SSP.EventTrigger())
        self.btnCap.clicked.connect(lambda:SSP.TakePictures())
        WUI.UIObj["TIMECAM"].timeout.connect(lambda:SSP.ShowCamera())
        self.btnDisplay.clicked.connect(lambda:DP.EventTrigger())
        self.btnGroup.buttonClicked.connect(lambda:DP.Selected())
        self.btnAI.clicked.connect(lambda:AI.EventTrigger())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setupEvent(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
